BoatRental.Web/Controllers/BoatController.cs
using BoatRental.Domain.Models;
using BoatRental.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BoatRental.Web.Controllers
{
    public class BoatController : Controller
    {
        private readonly IBookingRepository _bookingRepository;
        private readonly IBoatRepository _boatRepository;


        public BoatController(IBookingRepository repository, IBoatRepository boatRepository)
        {
            _bookingRepository = repository;
            _boatRepository = boatRepository;
        }
        // GET: Boat
        public ActionResult Index()
        {
            return View(_boatRepository.GetAll().Where(x => x.IsRented == false).ToList());
        }

        public ActionResult ViewBoat(int BoatId)
        {
            var boat = _boatRepository.Get(BoatId);
            var booking = new Booking();

            booking.Boat = _boatRepository.Get(BoatId);

            return View(booking);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost, ActionName("Create")]
        public ActionResult Create (Boat boat)
        {
            _boatRepository.Add(boat);

            return RedirectToAction("Index");
        }
    }
}

BoatRental.Web/Controllers/BookingController.cs
using BoatRental.Domain;
using BoatRental.Domain.Models;
using BoatRental.Repository;
using System;
using System.Linq;
using System.Web.Mvc;

namespace BoatRental.Web.Controllers
{
    public class BookingController : Controller
    {
        private readonly IBookingRepository _bookingRepository;
        private readonly IBoatRepository _boatRepository;


        public BookingController(IBookingRepository repository, IBoatRepository boatRepository)
        {
            _bookingRepository = repository;
            _boatRepository = boatRepository;
        }

        public ActionResult Index()
        {   
            return View();
        }

        [HttpPost]
        public ActionResult BookBoat(Booking Viewbooking)

        {
            int BoatId = Convert.ToInt32(Viewbooking.BoatId);
            int TotalHours = Convert.ToInt32(Viewbooking.EstimatedHours);

            //Build booking
            var boat = _boatRepository.Get(BoatId);
            Booking booking = new Booking();

            booking.BoatId = BoatId;
            booking.CustmerSSN = Viewbooking.CustmerSSN;
            booking.StartDate = DateTime.Now;
            booking.EstimatedPrice = boat.GetPrice(TotalHours);
            booking.EstimatedEndDate = DateTime.Now.AddHours(TotalHours);
            booking.EstimatedHours = TotalHours;
            booking.IsActive = true;
            boat.IsRented = true;

            //Send back Calcelated booking with its Boat to view for confirmation

            booking.Boat = boat;

            return View ("~/Views/Booking/ConfirmBooking.cshtml", booking);
        }

        [HttpPost]
        public ActionResult ViewBooking(string bookingId)
        {
            //Get the booking from DB and return to view for recalc and confirmation.
            int BookingId = -1;
            try
            {
                BookingId = Convert.ToInt32(bookingId);
            }
            catch (Exception x){}

            var booking = _bookingRepository.Get(BookingId);

            if(booking != null)
            {
                booking.Boat = _boatRepository.Get(booking.BoatId);
                booking.RecievedDate = DateTime.Now;
                booking.IsActive = false;

                var boat = _boatRepository.Get(booking.BoatId);

                decimal BookedMinutes = ((DateTime.Now - booking.StartDate).Minutes);

                decimal BookedHouersD = Math.Ceiling(Decimal.Divide(BookedMinutes, 60));

                int BookedHouers = Convert.ToInt32(BookedHouersD);

                booking.RecievedPrice = boat.GetPrice(BookedHouers);

                return View(booking);
            }
            else
            {
                ModelState.AddModelError("Id", "Bokningsnummer stämmer ej med någon bokning!");
                return View("Index");
            }
        }
        
        [HttpPost]
        public ActionResult ConfirmBooking(Booking booking)
        {
            var boat = _boatRepository.Get(booking.BoatId);

            //Update boat (Booked)
            boat.IsRented = true;
            _boatRepository.Update(boat);

            //Add new booking
            _bookingRepository.Add(booking);

            return View("~/Views/Booking/BookingConfirmed.cshtml", booking);
        }

        public ActionResult EndBooking(Booking booking)
        {
            //End booking confirmed, update DB.
            var boat = _boatRepository.Get(booking.BoatId);

            _bookingRepository.Update(booking);

            boat.IsRented = false;
            _boatRepository.Update(boat);

            return View("Index");
        }
    }
 

    public static class Ext
    {
        public static double GetPrice(this Boat boat, int totalHours)
        {
            var grundPrice = 200;
            double returnPrice = 0;

            switch (boat.Category)
            {
                case BoatCategory.Jolle:
                    returnPrice = grundPrice + (boat.PricePerHour * totalHours);
                    break;
                case BoatCategory.Over40:
                    returnPrice = (grundPrice * 1.2) + (boat.PricePerHour * 1.3 * totalHours);
                    break;
                case BoatCategory.Under40:
                    returnPrice = (grundPrice * 1.5) + (boat.PricePerHour * 1.4 * totalHours);
                    break;
            }

            return returnPrice;
        }
    }
}

BoatRental.Web/Controllers/HomeController.cs
using BoatRental.Domain;
using BoatRental.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BoatRental.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly IBoatRepository _boatRepository;
        public HomeController(BoatRepository boatRepository)
        {
            _boatRepository = boatRepository;
        }

        public ActionResult Index()
        {
            return View();
        }
    }
}

BoatRental.Web/Views/Boat/Create.cshtml
@model BoatRental.Domain.Models.Boat

@{
    ViewBag.Title = "Lägg till ny båt";
}

<h2>Skapa ny</h2>

@using (Html.BeginForm("Create", "Boat", Model)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Boat</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PricePerHour, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PricePerHour, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PricePerHour, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Category, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Category, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Category, "", new { @class = "text-danger" })

            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Skapa" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Tillbaka", "Index")
</div>

BoatRental.Web/Views/Boat/Index.cshtml
@model List<BoatRental.Domain.Models.Boat>
@{
    ViewBag.Title = "Båtar";
}

<h2>Tillgängliga båtar</h2>


<div class="container">
    <div class="row">
        <div class="col-12">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col">Namn</th>
                        <th scope="col">Pris(h)</th>
                        <th scope="col">Kategori</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody>

                    @foreach (var boat in Model.Where(x => x.IsRented == false))
                    {
                        <tr>
                            <th scope="row">@boat.Id</th>
                            <td>@boat.Name</td>
                            <td>@boat.PricePerHour</td>
                            <td>@boat.Category.ToString()</td>
                            <td>

                                @using (Html.BeginForm("ViewBoat", "Boat", FormMethod.Post))
                                {
                                    <input type="hidden" name="BoatId" id="BoatId" value="@boat.Id">
                                    <input type="submit" value="Välj" class="btn btn-primary" />
                                }
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
    <div>
        @Html.ActionLink("Lägg till båt", "Create")
    </div>
</div>

BoatRental.Web/Views/Boat/ViewBoat.cshtml
@model BoatRental.Domain.Models.Booking
@{
    ViewBag.Title = "Boka båt";
}

<h2>Tillgänglig båt</h2>
<div class="container">
    <div class="row">
        <div class="col-12">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col">Namn</th>
                        <th scope="col">Pris(h)</th>
                        <th scope="col">Kategori</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <th scope="row">@Model.Boat.Id</th>
                        <td>@Model.Boat.Name</td>
                        <td>@Model.Boat.PricePerHour</td>
                        <td>@Model.Boat.Category.ToString()</td>

                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

@using (Html.BeginForm("BookBoat", "Booking", FormMethod.Post))
{


<div class="form-horizontal">
    <div class="form-group">
        @Html.LabelFor(model => model.BoatId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.BoatId, new { htmlAttributes = new { @class = "form-control", @readonly= "readonly" } })
            @Html.ValidationMessageFor(model => model.BoatId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EstimatedHours, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EstimatedHours, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EstimatedHours, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CustmerSSN, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CustmerSSN, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CustmerSSN, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        <div class="col-md-offset-9 col-md-10">
            <input type="submit" value="Boka" class="btn btn-primary" />
        </div>
    </div>
</div>
}

BoatRental.Web/Views/Booking/BookBoat.cshtml
@model BoatRental.Domain.Models.Booking

@{
    ViewBag.Title = "BookBoat";
}

<h2>BookBoat</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Booking</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustmerSSN, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustmerSSN, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustmerSSN, "", new { @class = "text-danger" })
            </div>
        </div>

    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BoatRental.Web/Views/Booking/BookingConfirmed.cshtml
@model BoatRental.Domain.Models.Booking
@{
    ViewBag.Title = "BookingConfirmed";
}

<h2>Tack för din bokning!</h2>

<h3>Din bokningsnummer är ( #<strong>@Model.Id</strong> ), denna behöver du för att avboka.</h3>
<br />
<button class="btn btn-info">@Html.ActionLink("Tillbaka", "Index", "Boat")</button>

BoatRental.Web/Views/Booking/ConfirmBooking.cshtml
@model BoatRental.Domain.Models.Booking
@{
    ViewBag.Title = "Boka";
}

<h2>Tillgänglig båt</h2>

@using (Html.BeginForm("ConfirmBooking", "Booking", Model))
{
    <div class="container">
        <div class="row">
            <div class="col-12">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th scope="col">ID</th>
                            <th scope="col">Namn</th>
                            <th scope="col">Båt Kategori</th>
                            <th scope="col">Pris(h)</th>
                            <th scope="col">Personnummer</th>
                            <th scope="col">Antal timmar</th>
                            <th scope="col">Datum för återlämning</th>
                            <th scope="col">Total pris</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <th scope="row">@Model.Boat.Id</th>
                            <td>@Model.Boat.Name</td>
                            <td>@Model.Boat.Category.ToString()</td>
                            <td>@Model.Boat.PricePerHour</td>
                            <td>@Model.CustmerSSN</td>
                            <td>@Model.EstimatedHours</td>
                            <td>@Model.EstimatedEndDate</td>
                            <td>@Model.EstimatedPrice SEK</td>

                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <div class="form-horizontal">
        <div class="form-group">
            <div class="col-md-offset-11 col-md-11">
                <input type="submit" value="Boka" class="btn btn-success" />
            </div>
        </div>
    </div>
}

BoatRental.Web/Views/Booking/Index.cshtml
@model BoatRental.Domain.Models.Booking
@{
    ViewBag.Title = "Index";
}

<h2>Hantera Bookning</h2>
<h3>Nedna kan du visa och återlämna båten.</h3>

@using (Html.BeginForm("ViewBooking", "Booking", FormMethod.Post))
{
    <strong class="text-danger">@Html.ValidationMessageFor(m => m.Id)</strong>
    <div class="input-group mb-3">

        <input type="number" class="form-control" placeholder="Bokningsnummer..." aria-label="Bokningsnummer..." aria-describedby="basic-addon2" name="bookingId" data-val-number="The field EstimatedHours must be a number.">
        <div class="input-group-append">
            <br />
            <button class="btn btn-outline-secondary" type="submit">Återlämna</button>

        </div>
    </div>

}

BoatRental.Web/Views/Booking/ViewBooking.cshtml
@model BoatRental.Domain.Models.Booking
@{
    ViewBag.Title = "Boka";
}

<h2>Hantera bokning</h2>

@using (Html.BeginForm("EndBooking", "Booking", Model))
{
    <div class="container">
        <div class="row">
            <div class="col-12">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th scope="col">Nummer</th>
                            <th scope="col">Namn</th>
                            <th scope="col">Båt Kategori</th>
                            <th scope="col">Pris(h)</th>
                            <th scope="col">Personnummer</th>
                            <th scope="col">Uthyrningsdatum</th>
                            <th scope="col">Reserverade timmar</th>
                            <th scope="col">Datum för återlämning</th>
                            <th scope="col">Reserverat Pris</th>
                            <th scope="col">Återlämnings datum</th>
                            <th scope="col">Total belopp</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <th scope="row">@Model.Id</th>
                            <td>@Model.Boat.Name</td>
                            <td>@Model.Boat.Category.ToString()</td>
                            <td>@Model.Boat.PricePerHour</td>
                            <td>@Model.CustmerSSN</td>
                            <td>@Model.StartDate.ToString("MM/dd/yyyy H:mm")</td>
                            <td>@Model.EstimatedHours</td>
                            <td>@Model.EstimatedEndDate.ToString("MM/dd/yyyy H:mm")</td>
                            <td>@Model.EstimatedPrice SEK</td>
                            <td>@Model.RecievedDate</td>
                            <td>@Model.RecievedPrice SEK</td>

                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <div class="form-horizontal">
        <div class="form-group">
            <div class="col-md-offset-11 col-md-11">
                <input type="submit" value="Avsluta" class="btn btn-success" />
            </div>
        </div>
    </div>
}

BoatRental.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Hello World!";
}

<div class="jumbotron">
    <h1>L8's båtuthyrnings plattform</h1>
    <p class="lead">Hej och välkommen in till min plattform, ovan i menyn kan ni navigera bland olika funktioner, nedan är en kort specifikation.</p>
    <p>För att boka, vänligen välj "Boats" för att sedan välje en bås som passar er, annars kan ni lägga upp drömbåten via samma vy (längs ner "Lägg till båt"). För att avsluta bokningen och återlämna båten. vänligen gå till "Bookings" och mata in ert boknings nummer.</p>
</div>

BoatRental.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("BoatRental", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Bookings", "Index", "Booking")</li>
                    <li>@Html.ActionLink("Boats", "Index", "Boat")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Layth Nasser </p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>